In [1]:
def minimum_search1(extreme1, interval_length, measures_number, degree, delta):
    
    X = np.random.uniform(extreme1,extreme1 + interval_length, measures_number)
    Xcopy = Xcopy2 = X 
    
    print X
    step = 0 
    
    while True:
        step += 1
        Xcopy2 = Xcopy
        
        
        for i in xrange(measures_number):
            W = np.matrix([ [x**j for j in range(degree+1)] for x in X])
            Cb = np.linalg.inv(np.matmul(W.transpose(),W))
            Xcopy[i] = X[i]+delta
            Wcopy = np.matrix([ [x**j for j in range(degree+1)] for x in Xcopy])
            Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))  
            print 'ok'
            
            if np.count_nonzero(np.triu(np.absolute(Cbcopy)) < np.triu(np.absolute(Cb))) > (degree+1)(degree+2)/2:    
                X[i] = Xcopy[i]
                print 'O+'
            
            else:
                Xcopy[i] = Xcopy[i]-2*delta
                Wcopy= np.matrix([ [x**j for j in xrange(degree+1)] for x in Xcopy])
                Cbcopy=np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))
                
                if np.count_nonzero(np.triu(np.absolute(Cbcopy)) < np.triu(np.absolute(Cb))) > (degree+1)(degree+2)/2:    
                    X[i] = Xcopy[i]
                    print 'O-'
                else:
                    Xcopy[i] = X[i]
                
        if (np.linalg.norm(Xcopy - Xcopy2) < 0.001): 
            Cb = Cbcopy
            
            break 
            #if (Xcopy[i]>3 or Xcopy[i]<-3):
                #break
        #print X
        #print Cb
    return X, Cb, step
    

In [ ]:
X=np.random.uniform(-3,3,N)
Xcopy=X
Xcopy2=X 
print X
delta=0.1
step=0
while True:
    Xcopy2 = Xcopy
    step+=1
    print step
    for i in range(0,N,1):
        W=np.matrix([ [x**j for j in range(g+1)] for x in X])
        Cb=np.linalg.inv(np.matmul(W.transpose(),W))
        Xcopy[i]=X[i]+delta
        Wcopy= np.matrix([ [x**j for j in range(g+1)] for x in Xcopy])
        Cbcopy=np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))  
        print 'ok'
        check=0
        for col in range(0,g+1):
            for row in range(0,g+1):
                if (Cbcopy.item((row,col))<=Cb.item((row,col))):
                    check+=1
        if (check>=(g+1)**2/2):    
            X[i]=Xcopy[i]
            print 'O+'
        else:
            Xcopy[i]=X[i]-2*delta
            Wcopy= np.matrix([ [x**j for j in range(g+1)] for x in Xcopy])
            Cbcopy=np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))
            check=0
            for col in range(0,g+1):
                for row in range(0,g+1):
                    
                    if (np.absolute(Cbcopy.item((row,col)))<=np.absolute(Cb.item((row,col)))):
                        check+=1
            if (check>=(g+1)**2/2):    
                X[i]=Xcopy[i]
                print 'O-'
            else:
                pass
        if (np.linalg.norm(Xcopy - Xcopy2) < 0.001): 
            break 
        #if (Xcopy[i]>3 or Xcopy[i]<-3):
            #break
    #print X
    #print Cb

print 'la matrice di covarianza minima trovata è'
print Cb
print 'le x a cui corrisponde la Cb minima è'
print X

In [ ]:
def minimum_search3(extreme1, interval_length, measures_number, degree, delta):
    
    X = Xcopy = Xcopy2 = np.random.uniform(extreme1,extreme1 + interval_length, measures_number)
    
    step = 0 
    
    while True: 
        
        Xcopy2 = Xcopy
        step += 1
        
        v = np.random.normal(0, 1, measures_number) 
        DX = delta*v/np.linalg.norm(v)
        
        W = np.matrix([ [x**j for j in range(g+1)] for x in X])
        Cb = np.linalg.inv(np.matmul(W.transpose(),W))
        
        Xcopy = X + DX 
        Wcopy= np.matrix([ [x**j for j in xrange(degree+1)] for x in Xcopy])
        Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))
        
        if np.count_nonzero(np.triu(Cbcopy) < np.triu(Cb)) > (degree+1)(degree+2)/2:    
                X = Xcopy
            
        else: 
            
            Xcopy = Xcopy - 2*DX
            Wcopy = np.matrix([ [x**j for j in xrange(degree+1)] for x in Xcopy])
            Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))
            
            if np.count_nonzero(np.triu(Cbcopy) < np.triu(Cb)) > (degree+1)(degree+2)/2:    
                    X = Xcopy
                   
            else:
                Xcopy = X
    
        if (np.linalg.norm(Xcopy - Xcopy2) < 0.001): 
            Cb = Cbcopy
            
            break 
    
    return X, Cb, step 
    
    

In [40]:
def minimum_search2_(extreme1, interval_length, measures_number, degree, delta):
    
    X = np.random.uniform(extreme1,extreme1 + interval_length, measures_number)
    Xcopy = X 
    
    print X
    step = 0 
    
    while (step <= 2000):
        step += 1
        
        DX = np.zeros(measures_number)
        
        for i in xrange(measures_number):
            
            Xcopy = X 
            
            W = np.matrix([ [x**j for j in range(degree+1)] for x in X])
            Cb = np.linalg.inv(np.matmul(W.transpose(),W))
            Xcopy[i] = X[i]+delta
            Wcopy = np.matrix([ [x**j for j in range(degree+1)] for x in Xcopy])
            Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))  
            
            
            if np.count_nonzero(np.triu(np.absolute(Cbcopy)) < np.triu(np.absolute(Cb))) > (degree+1)*(degree+2)/4:    
                DX[i] = delta
                
            
            else:
                Xcopy[i] = Xcopy[i]-2*delta
                Wcopy = np.matrix([ [x**j for j in xrange(degree+1)] for x in Xcopy])
                Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))
                
                if np.count_nonzero(np.triu(np.absolute(Cbcopy)) < np.triu(np.absolute(Cb))) > (degree+1)*(degree+2)/4:    
                    DX[i] = -delta 
                    
                else:
                    DX[i] = 0 
                    
        
        X += DX
        #print(X, Xcopy2, DX)
                
        #if np.array_equal(DX, np.zeros(measures_number)) : 
            #Cb = Cbcopy
            
            
            
    return X, Cb, step
    

In [22]:
def minimum_search1(extreme1, interval_length, measures_number, degree, delta):
    
    X = np.random.uniform(extreme1,extreme1 + interval_length, measures_number)
    Xcopy = X 
    
    print X
    step = 0 
    
    while True:
        step += 1
        
        
        DX = np.zeros(measures_number)
        
        for i in xrange(measures_number):
            
            Xcopy = X 
            
            W = np.matrix([ [x**j for j in range(degree+1)] for x in X])
            Cb = np.linalg.inv(np.matmul(W.transpose(),W))
            
            if (Xcopy[i] > (extreme1 + interval_length) - delta): 
                pass
            else: 
                Xcopy[i] = X[i]+delta 
                
            Wcopy = np.matrix([ [x**j for j in range(degree+1)] for x in Xcopy])
            Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))  
            
            
            if np.count_nonzero(np.triu(np.absolute(Cbcopy)) < np.triu(np.absolute(Cb))) > (degree+1)*(degree+2)/4:    
                DX[i] = delta
                
            
            else:
                if (Xcopy[i] < (extreme1 + delta)):
                    pass
                else: 
                    Xcopy[i] = Xcopy[i]-2*delta
                    
                Wcopy = np.matrix([ [x**j for j in xrange(degree+1)] for x in Xcopy])
                Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))
                
                if np.count_nonzero(np.triu(np.absolute(Cbcopy)) < np.triu(np.absolute(Cb))) > (degree+1)*(degree+2)/4:    
                    DX[i] = -delta 
                    
                else:
                    DX[i] = 0 
        
        X += DX
        #print(X, Xcopy2, DX)
        W2 = np.matrix([ [x**j for j in range(degree+1)] for x in Xcopy])
        Cb2 = np.linalg.inv(np.matmul(W2.transpose(),W2))
                
       
            
        if step>9500 and step<10000:
            
            print'x', X
            print 'dx',DX
            print 'Cb',Cb
        
                
        if np.array_equal(DX, np.zeros(measures_number)) or\
        np.count_nonzero(np.triu(np.absolute(Cb)) < np.triu(np.absolute(Cb2))) > (degree+1)*(degree+2)/4 \
        or(step>10000): 
            
            xg = np.sum(X)/measures_number
            sk = np.sum(X**3)/(measures_number)
                    
            return X, Cb, xg, sk, step
    

In [45]:
import numpy as np 
import time 
from numba import jit

In [24]:
start = time.time()

X, Cb, xg , sk, step = minimum_search1(-3,6,16,2,0.001)

end = time.time()

print 'la matrice di covarianza minima trovata è \n {}'.format(Cb)
    
print 'le x a cui corrisponde la Cb minima è \n {}'.format(X)
    
print 'il baricentro delle misure è {}'.format(xg)

print 'la skewness delle misure è {}'.format(sk)



[ -1.20037749e+00   2.58447658e+00   1.36439309e+00  -1.30208650e+00
   2.98875887e+00  -1.23844633e+00   2.45087304e-01  -6.11659408e-01
  -2.41150535e+00  -1.90438285e+00   3.59615982e-02   1.76704064e-03
   9.60960700e-01  -1.86734050e+00  -3.65821474e-01   1.34366268e+00]
x [-0.16237749  2.99847658 -0.08660691 -0.1620865   2.99975887 -0.16144633
 -0.1629127  -0.16265941 -2.99950535 -2.99938285 -0.1620384  -0.16023296
 -0.0850393  -3.0013405  -0.16182147 -0.08633732]
dx [ 0.     0.     0.     0.     0.001  0.001  0.     0.     0.     0.     0.
  0.001  0.001 -0.001  0.     0.001]
Cb [[ 0.09179445  0.00324376 -0.01003977]
 [ 0.00324376  0.02315702  0.00118793]
 [-0.01003977  0.00118793  0.00367279]]
x [-0.16037749  3.00047658 -0.08760691 -0.1600865   2.99775887 -0.16244633
 -0.1609127  -0.16365941 -3.00150535 -3.00138285 -0.1630384  -0.16123296
 -0.0860393  -3.0003405  -0.16282147 -0.08733732]
dx [ 0.001  0.001  0.     0.001  0.     0.     0.001  0.    -0.001 -0.001  0.
  0.     0.  

In [57]:
from numba import jit 

In [75]:
def minimum_search(extreme1, interval_length, measures_number, degree, delta, alfa):
    
    X = np.random.uniform(extreme1,extreme1 + interval_length, measures_number)
    Xcopy = X 
    DX = np.ones(measures_number)
    
    print X
    step = 0 
    
    
    while np.linalg.norm(DX/alfa) > 0.001: 
        
        step += 1
        
        W = np.matrix([ [x**j for j in xrange(degree+1)] for x in X])
        Cb = np.linalg.inv(np.matmul(W.transpose(),W))
        
        DX = np.zeros(measures_number)
        
        for i in xrange(measures_number):
            
            Xcopy = X 
            
            if Xcopy[i] > ((extreme1 + interval_length) - delta):
                pass
            elif Xcopy[i] < (extreme1 + delta): 
                pass
            else: 
                Xcopy[i] = X[i]+delta 
            
            
            Wcopy = np.matrix([ [x**j for j in xrange(degree+1)] for x in Xcopy])
            Cbcopy = np.linalg.inv(np.matmul(Wcopy.transpose(),Wcopy))  
            
            DX[i] = - alfa * ((np.linalg.norm(Cbcopy) - np.linalg.norm(Cb))/delta)
            
        X = X + DX
            
        if step%1001 == 0: 
            print'x', X
            print 'norm_g',np.linalg.norm(DX/alfa)
            print 'DX', DX
            print 'Cb',Cb 
     
            
            
    W2 = np.matrix([ [x**j for j in xrange(degree+1)] for x in X])
    Cb2 = np.linalg.inv(np.matmul(W2.transpose(),W2))
            
    xg = np.sum(X)/measures_number
    sk = np.sum(X**3)/(measures_number)
    
    
                    
    return X, Cb2, xg, sk, step
            
         
            
            
            

In [77]:
start = time.time()

X, Cb, xg , sk, step = minimum_search(-3,6,2,1,delta = 0.0001,alfa = 0.01)

end = time.time()

print 'la matrice di covarianza minima trovata è \n {}'.format(Cb)
    
print 'le x a cui corrisponde la Cb minima è \n {}'.format(X)
    
print 'il baricentro delle misure è {}'.format(xg)

print 'la skewness delle misure è {}'.format(sk)

print 'il tempo impiegato è {}'.format(end-start)



[ 2.89471856  2.74924833]
x [ 116.58270154   -2.64219658]
norm_g 0.0156786093064
DX [-0.         -0.00015679]
Cb [[  9.56660251e-01  -8.01576267e-03]
 [ -8.01576267e-03   1.40700775e-04]]
x [ 116.58270154   -2.6988883 ]
norm_g 0.0156484753799
DX [-0.         -0.00015648]
Cb [[  9.55772387e-01  -8.00416051e-03]
 [ -8.00416051e-03   1.40567062e-04]]
x [ 116.58270154   -2.7552795 ]
norm_g 0.0156185653133
DX [-0.         -0.00015619]
Cb [[  9.54890922e-01  -7.99263814e-03]
 [ -7.99263814e-03   1.40434248e-04]]
x [ 116.58270154   -2.81137241]
norm_g 0.0155888767406
DX [-0.         -0.00015589]
Cb [[  9.54015791e-01  -7.98119476e-03]
 [ -7.98119476e-03   1.40302322e-04]]
x [ 116.58270154   -2.86716925]
norm_g 0.0155594073337
DX [-0.         -0.00015559]
Cb [[  9.53146930e-01  -7.96982961e-03]
 [ -7.96982961e-03   1.40171277e-04]]
x [ 116.58270154   -2.92267218]
norm_g 0.0155301547933
DX [-0.        -0.0001553]
Cb [[  9.52284274e-01  -7.95854192e-03]
 [ -7.95854192e-03   1.40041105e-04]]
x [ 

In [9]:
import scipy
from scipy import optimize, stats 
import numpy as np

def cov_norm(X, degree=2): 
    
    W = np.matrix([ [x**j for j in xrange(degree+1)] for x in X])
    Cb = np.linalg.inv(np.matmul(W.transpose(),W))
    norm = np.linalg.norm(Cb)
    
    return norm 

def cov_tr(X, degree=2): 
    
    W = np.matrix([ [x**j for j in xrange(degree+1)] for x in X])
    Cb = np.linalg.inv(np.matmul(W.transpose(),W))
    trace = np.trace(Cb)
    return trace 
    
def optimize(measures_number,extreme1, interval_length,degree, fun):
    
    limits = [(extreme1,extreme1+ interval_length) for i in xrange(measures_number)]
    Xin = np.random.uniform(extreme1,extreme1 + interval_length, measures_number)
    
    return scipy.optimize.minimize(fun, Xin, jac=None, hess=None, hessp=None, bounds = limits,\
    tol=None, callback=None, options=None)
    
    
    
    
        
    

In [10]:
N = 1000
x1 = -3 
L = 6 
deg = 3
fun = cov_tr


In [11]:
Res = optimize(N,x1,L,deg,fun)

In [12]:
X = Res['x']
xg = np.sum(X)/len(X)
sk = np.sum(X**3)/len(X)
five = np.sum
kur = stats.kurtosis(X,fisher = True )
W = np.matrix([ [x**j for j in xrange(deg+1)] for x in X])
Cb = np.linalg.inv(np.matmul(W.transpose(),W))
print 'il baricentro delle misure è {}'.format(xg)
print 'la skewness delle misure è {}'.format(sk)
print 'la kurtosis delle misure è {}'.format(kur)
print 'la matrice di covarianza delle misure è \n{}'.format(Cb)

il baricentro delle misure è 0.0305373621305
la skewness delle misure è 0.161860577141
la kurtosis delle misure è -1.23452993308
la matrice di covarianza delle misure è 
[[ 2.31623975e-03 -1.25528397e-04 -4.28377319e-04  2.30690170e-05]
 [-1.25528397e-04  2.16670063e-03  3.72192872e-05 -3.39730257e-04]
 [-4.28377319e-04  3.72192872e-05  1.39449964e-04 -7.43450796e-06]
 [ 2.30690170e-05 -3.39730257e-04 -7.43450796e-06  6.26905328e-05]]
